### ISSUE TITLE
Script for data generation

### ISSUE THREAD

**Issue by LewiVir** [wsyCUHK/WSYCUHK_FDIA#3]
Hello,

I'm very interested in your work, especially the min-cut method for attack generation. I noticed your repository named "FDIA_DBN" which is, in my understanding, the script for data generation. But it seems incomplete for the absence of "matlan-bgl", "MILP", some case*.mat files and so on. Could you please provide a fully-functional version of it? I'd really appreciate your kind help.

Best regards.

**Comment by arbab97** [comment]
@chl17 were you able to get the scripts for data generation? I will really appreciate if you can share them with me. Or if you found any alternative, I would love to know. 
Thanks,
