### ISSUE TITLE
Five Variants of Dataset

### ISSUE THREAD

**Issue by arbab97** [wsyCUHK/WSYCUHK_FDIA#7]
Dear Dr. Wang, 
I hope you are doing well. Can you kindly confirm if the five variants of the dataset provided on the GitHub (i.e. data14_1, data14_2 ... data14_5) vary in the L-2 norm of the injection data or the level of noise? 
The push comment mentions '14 Bus System data with different size of noise' however, I am getting better results with data14_5 as compared to data14_1. But if the level of noise is increasing from data14_1 to data14_5, then the performance should decrease.  Then I see the two possibilities are:
1) The provided datasets vary in the L-2 norm since the performance increases from variant # 1 to 5. (Ref: Figure 5a in your paper)
2) The provided datasets vary in the level of noise BUT the level of noise increases from level 5 to level 1 i.e. in reverse. 
Can you kindly comment? It'll be a huge help. 
Best Regards, 
Arbab

@wsyCUHK

**Comment by wsyCUHK** [comment]
Hi, arbab
     Sorry for the misleading. The provided datasets actually vary in the L-2 norm since the performance increases from variant # 1 to 5.

**Comment by arbab97** [comment]
Thank you for your clarification. 
Best Regards,
